const plantList = [
  {
    _id: '1',
    name: 'Nasturtium',
    fact: 'You can eat the whole plant including seeds! Make a flower salad.',
    water: 'Once or twice a week',
    spot: 'Relishes in full sun!',
    info: '',
  },
  {
    _id: '2',
    name: 'Aloe Vera',
    fact: 'You can eat it or use it for skin care!',
    water: 'Once a week',
    spot: 'The plant can be positioned in full or indirect sunlight',
    info: '',
  },
  {
    _id: '3',
    name: 'Black Gold Philodendron melanochrysum ',
    fact: ' This plant purifies the air',
    water:
      ' Water freely when in full growth and add a monthly liquid feed; water sparingly in winter',
    spot: 'Bright location with indirect sunlight ',
    info: ' Grow it up a moss pole and spray regularly to create humidity ',
  },
  {
    _id: '4',
    name: 'Aglaonema Chinese Evergreen',
    fact: 'Aglaonema have been grown as luck-bringing ornamental plants in Asia for centuries',
    water:
      ' Water your Aglaonema when the top 50% of the soil is dry. Water until liquid flows through the drainage hole at the bottom of the pot and discard any water that has accumulated in the saucer. ',
    spot: 'The plant can be placed near a window on the west or east, as long as there is 1 to 2 meters space between the plant and the window, so that it still catches some shade. Calatheas thrive in medium to bright indirect light, but can tolerate low indirect light. ',
    info: ' The NASA Clean Air Study determined that the species modestum of this plant genus was effective at removing common household air toxins formaldehyde and benzene. ',
  },
  {
    _id: '5',
    name: 'White Fusion Calathea',
    fact: 'The calathea comes from the tropical forests of South America. In the rain forests they grow in the shade of trees and other large plants, which is why they are also calles "shade plants".',
    water:
      ' Water every 1-2 weeks, allowing soil to dry out half way down between waterings. Expect to water more often in brighter light and less often in lower light.',
    spot: ' Calatheas thrive in medium to bright indirect light, but can tolerate low indirect light. ',
    info: ' The plant has the unique property that it has its leaves folded at night and folds out again during the day ',
  },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
  { name: '', fact: '', water: '', spot: '', info: '' },
];
export default plantList;
